name: Deploy HTML site

on:
  push:
    branches: [ "main" ]   # deploy whenever you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: E:\To be a Dev\Projects\Favourite Music Artist\Vocaloid Music Artists Web Collection   # folder where your HTML files are